# Generated by Django 3.2.3 on 2021-05-27 20:32

import beer_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='beer description'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=beer_app.models.image_upload_path, verbose_name='beer image'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='mark',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[beer_app.models.RangeValidator(0, 10)], verbose_name='beer mark'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Beer price in UAH', max_digits=5, validators=[beer_app.models.RangeValidator(0, 1000)], verbose_name='beer price'),
        ),
    ]
