language: python

stages:
  - test
  - collect_static
  - deploy

install:
  - pip install pipenv
  - pipenv install

jobs:
  include:
    - stage: test
      name: "Test"
      services:
        - postgresql
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
      script: python manage.py test -v2
      env:
        - POSTGRES_DB=travis_ci_test
        - POSTGRES_HOST=localhost
        - POSTGRES_USER=postgres
        - SECRET_KEY=secret
        - USE_S3=False

    - stage: deploy
      name: "Deploy"
      services:
        docker
      script: 
        # - make static
        # - make build_image
        - ssh-keygen -f ~/.ssh/aws_key -N ''
        - echo "$SSH_KEY" | base64 -d >  ~/.ssh/aws_key
        - cat  ~/.ssh/aws_key
        - chmod 700 ~/.ssh/aws_key
      deploy:
        provider: script
        script: bash ./deploy.sh ${SSH_USER}@${SSH_ADDRESS}
        skip_cleanup: true
      if: branch = master
      env:
        - SSH_USER=ubuntu
        - SSH_ADDRESS=35.158.232.255
        - USE_S3=True
        - SECRET_KEY=secret
        - POSTGRES_DB=travis_ci_test
        - POSTGRES_HOST=localhost
        - POSTGRES_USER=postgres
