language: python


install:
  - make
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script: make test
env:
  global:
    - POSTGRES_DB=travis_ci_test
    - POSTGRES_HOST=localhost
    - POSTGRES_USER=postgres
    - SECRET_KEY=secret
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: beer-rating-533-backend
  strategy: git
